const $ = id => document.getElementById(id);
const stateLabels = {queued:'대기',resolving:'표적 확인 중',collecting:'문헌 수집 중',awaiting_selection:'표적 선택 필요',completed:'수집 완료',partial:'일부 확인 필요',not_found:'표적 미확인',unsupported:'지원 범위 밖',failed:'작업 실패',interrupted:'중단됨'};
const formatLabels = {jats_xml:'JATS XML',pdf:'첨부 PDF',abstract_text:'초록',metadata:'메타데이터'};
let activeRun = null, pollTimer = null, lastStamp = null;
function node(tag, text, className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'X-TPD-Local':'1',...(options.headers||{})}});const value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'요청 내용을 확인해 주세요.');return value;}
function link(text,url){const a=node('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function notice(text){return node('div',text,'notice');}
async function history(){const rows=await api('/api/runs');$('history-list').replaceChildren();for(const row of rows){const b=node('button');b.append(node('span',row.query),node('small',stateLabels[row.state]||row.state));b.onclick=()=>openRun(row.id);$('history-list').append(b);}}
async function openRun(id){activeRun=id;lastStamp=null;clearTimeout(pollTimer);$('empty').hidden=true;$('run-view').hidden=false;await refresh();}
async function refresh(){const id=activeRun;try{const run=await api('/api/runs/'+id);if(activeRun!==id)return;const stamp=run.updated_at+JSON.stringify(run.analyses)+JSON.stringify((run.workflows||[]).map(w=>[w.id,w.state,w.updated_at]));if(lastStamp!==stamp){render(run);lastStamp=stamp;}if((['queued','resolving','collecting'].includes(run.state)||(run.analyses||[]).some(a=>['queued','running'].includes(a.state))||(run.workflows||[]).some(w=>['queued','running'].includes(w.state)))){pollTimer=setTimeout(refresh,1000);}else{history();}}catch(e){$('run-message').textContent=e.message;}}
function render(run){
 $('run-title').textContent=run.request.query;$('run-state').textContent=stateLabels[run.state]||run.state;$('run-state').className='badge'+(['partial','failed','unsupported','interrupted'].includes(run.state)?' warn':'');$('run-message').textContent=run.message;
 $('target-card').replaceChildren();$('selection').replaceChildren();$('documents').replaceChildren();$('metrics').replaceChildren();$('run-notices').replaceChildren();$('evidence-heading').hidden=!run.bundle;
 const target=run.target;if(target){if(target.selected_candidate_id){const c=target.candidates.find(c=>c.candidate_id===target.selected_candidate_id);const card=node('div',undefined,'target');card.append(node('h3',c.identity.label),link(c.identity.uniprot_accession,'https://www.uniprot.org/uniprotkb/'+encodeURIComponent(c.identity.uniprot_accession)));for(const reason of target.scope_reasons)card.append(node('p',reason));$('target-card').append(card);}else if(run.state==='awaiting_selection'){for(const c of target.candidates){const row=node('div',undefined,'selection-row');const text=node('div');text.append(node('strong',c.identity.label),node('p',c.identity.uniprot_accession+' · '+(c.identity.gene_symbol.value||'유전자명 미확인')));const b=node('button','이 표적 선택');b.onclick=async()=>{b.disabled=true;try{await api('/api/runs/'+run.id+'/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_id:c.candidate_id,revision:run.revision})});lastStamp=null;await refresh();}catch(e){$('run-message').textContent=e.message;b.disabled=false;}};row.append(text,b);$('selection').append(row);}target.scope_reasons.forEach(x=>$('selection').append(notice(x)));}}
 if(!run.bundle){for(const n of run.issues)$('run-notices').append(notice(n.message));}else{
  const b=run.bundle,c=b.coverage;for(const [label,value] of [['수집 문서',c.stored_document_count],['확보한 전문',c.fulltext_acquired_count],['추출 구간',c.extracted_segment_count],['분석 요청',(run.analyses||[]).length]]){const card=node('div',undefined,'metric');card.append(node('strong',String(value)),node('span',label));$('metrics').append(card);}
  for(const search of b.searches){const hits=search.total_hits.state==='known'?search.total_hits.value+'건':'미확인';$('run-notices').append(node('p','검색 결과 '+hits+' · 이번 수집은 요청한 문서 한도 내에서 수행했습니다.','hint'));search.issues.forEach(x=>$('run-notices').append(notice(x.message)));}
  for(const d of b.documents){const article=node('article',undefined,'document'),top=node('div',undefined,'document-top');const meta=node('div',undefined,'document-meta');meta.append(node('span',formatLabels[d.format]),node('span',d.extraction.status==='failed'?'추출 실패':d.extraction.status==='partial'?'텍스트 일부 추출':'텍스트 추출 완료'));top.append(meta,node('h3',d.title.value||'제목 미확인'));const links=node('div',undefined,'links');const origin=d.acquisition_paths.find(p=>p.external_uri&&/^https:\/\/europepmc\.org\//.test(p.external_uri));if(origin)links.append(link('출처 보기 ↗',origin.external_uri));if(d.source_artifact_ref)links.append(link('저장 원문 다운로드','/api/artifacts/'+encodeURIComponent(d.source_artifact_ref.artifact_id)+'/download'));top.append(links);for(const n of [...d.issues,...d.extraction.issues])top.append(notice(n.message));article.append(top);
   const segments=b.segments.filter(s=>s.locator.document_id===d.document_id),details=node('details',undefined,'segments');details.append(node('summary','원문 구간 '+segments.length+'개 확인'));let loaded=false;details.ontoggle=()=>{if(!details.open||loaded)return;loaded=true;for(const s of segments){const part=node('div',undefined,'segment'),loc=s.locator;part.append(node('small',loc.kind==='pdf'?'파일 '+loc.page+'페이지':loc.xpath||loc.field));const button=node('button','이 구간 읽기');button.onclick=async()=>{button.disabled=true;try{const result=await api('/api/artifacts/'+encodeURIComponent(s.text_artifact_ref.artifact_id)+'/text');part.append(node('p',result.text,'segment-text'));button.remove();}catch(e){button.disabled=false;button.textContent=e.message;}};part.append(button);addAnalysisSelection(part,s,run);details.append(part);}};article.append(details);$('documents').append(article);}
 }
 renderAnalysis(run);
 $('technical').textContent=JSON.stringify({run_id:run.id,input_revision:run.revision,data_mode:run.data_mode,jobs:run.jobs,target_ref:run.target_ref,bundle_ref:run.bundle_ref},null,2);
}
$('start-form').onsubmit=async event=>{event.preventDefault();$('form-error').textContent='';const button=$('start-button');button.disabled=true;try{const files=Array.from($('pdfs').files),max=Number($('max-documents').value);if(files.length>3||files.length>=max)throw Error('첨부는 최대 3개이며 검색을 위한 문서 한도를 남겨 주세요.');if(files.some(f=>f.size>6000000)||files.reduce((a,f)=>a+f.size,0)>10000000)throw Error('PDF는 파일당 6 MB, 합계 10 MB 이하로 선택해 주세요.');const ids=[];for(const file of files){const form=new FormData();form.append('file',file);button.textContent='첨부 자료 저장 중…';const result=await api('/api/uploads',{method:'POST',body:form});ids.push(result.artifact.artifact_id);}const result=await api('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:$('query').value,query_kind:$('query-kind').value,objective:$('objective').value,cell_line:$('cell-line').value,pdf_artifact_ids:ids,max_documents:max,request_key:crypto.randomUUID()})});await openRun(result.run_id);await history();}catch(e){$('form-error').textContent=e.message;}finally{button.disabled=false;button.textContent='문헌 탐색 시작 ↗';}};
history().catch(e=>$('form-error').textContent=e.message);
