'use strict';
const $=id=>document.getElementById(id);
const state={health:null,catalog:null,job:null,result:null,timer:null,pending:null,page:1,readOnly:false,selectedId:null,currentView:null};
const terminal=new Set(['completed','held','failed','cancelled','interrupted']);
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n}
function add(parent,...children){children.forEach(c=>c&&parent.appendChild(c));return parent}
function clear(n){while(n.firstChild)n.removeChild(n.firstChild)}
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
function value(v,fallback='—'){if(v===undefined||v===null||v==='')return fallback;if(Array.isArray(v))return v.map(x=>typeof x==='object'?`원자 ${x.atom_map}: ${x.state}`:String(x)).join(' · ');if(typeof v==='number')return v.toLocaleString('ko-KR',{maximumFractionDigits:3});if(typeof v==='object'&&'source_charge' in v)return `원 구조 전하 ${v.source_charge} → 별도 설계 상태 ${v.design_charge} · pH 예측 아님`;return String(v)}
function safeUrl(url){if(typeof url!=='string'||!/^https?:\/\//i.test(url.trim()))return null;try{const u=new URL(url.trim());return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function artifactId(ref){return ref&&typeof ref==='object'?(ref.artifact_id||ref.id):ref}
function artifactUrl(ref,preview=false){const id=artifactId(ref);return id?`${preview?'/api/lab/artifacts/':'/api/artifacts/'}${encodeURIComponent(id)}${preview?'/preview':'/download'}`:null}
function setError(message,code){const box=$('globalError');clear(box);add(box,node('b','',code==='PREVIOUS_VERSION'?'이전 실행 기록 안내':code?`요청 오류 (${code})`:'요청 오류'),node('span','',` ${message||'서버 응답을 확인할 수 없습니다.'}`));show('globalError',true)}
function clearError(){show('globalError',false);clear($('globalError'))}
async function api(url,options={}){const response=await fetch(url,options);let data=null;try{data=await response.json()}catch{}if(!response.ok){const e=new Error(data?.detail?.message||(Array.isArray(data?.detail)?data.detail.map(x=>`${x.loc?.join('.')}: ${x.msg}`).join('; '):data?.detail)||data?.message||`HTTP ${response.status}`);e.code=data?.code||data?.detail?.code||response.status;throw e}return data}
function setBusy(on){const blocked=on||state.readOnly;$('runButton').disabled=blocked;$('strictExample').disabled=blocked;$('dualExample').disabled=blocked;show('cancelButton',on);$('cancelButton').disabled=!on}
function updateRunLabel(){const llm=$('useApi').checked&&!$('useApi').disabled;$('runButton').textContent=llm?'설계 Agent 실행':'규칙 기반 실행'}
async function loadHealth(){try{const h=await api('/api/health');state.health=h;const llm=Boolean(h.llm_enabled??h.health?.llm_enabled);state.readOnly=Boolean(h.read_only||h.review_only);$('useApi').disabled=!llm||state.readOnly;$('useApi').checked=llm&&!state.readOnly;$('apiHelp').textContent=llm?'구성됨 · 선택 해제 시 규칙 기반 실행':'구성되지 않음 · 규칙 기반만 사용';$('healthBadge').textContent=state.readOnly?'읽기 전용':llm?'LLM 구성됨':'규칙 기반';$('healthBadge').className=`badge ${state.readOnly?'warning-badge':'ok'}`;if(state.readOnly)setError('서버가 읽기 전용 모드입니다. 기존 결과만 열 수 있습니다.','READ_ONLY');setBusy(Boolean(state.job&&!terminal.has(state.job.state)));updateRunLabel()}catch(e){$('healthBadge').textContent='상태 확인 실패';$('apiHelp').textContent='LLM 상태를 확인하지 못함';$('useApi').disabled=true;$('useApi').checked=false;updateRunLabel()}}
async function loadCatalog(open=false){try{state.catalog=await api('/api/design/catalog');fillLinkers();fillParents();window.TPDDesignEvidence?.render(state.catalog,state.result);if(open){renderCatalog();show('catalogPanel',true);$('catalogPanel').scrollIntoView({behavior:'smooth'})}}catch(e){setError(e.message,e.code)}}
function fillLinkers(){const filter=$('linkerFilter');const templates=state.catalog?.linkers?.templates||[];clear(filter);add(filter,new Option('전체','all'));templates.forEach(t=>add(filter,new Option(value(t.label,t.id),t.id)))}
function fillParents(){const select=$('parentId'),current=select.value||'SMARCA2-FX5',records=state.catalog?.reference_parents?.available||[];clear(select);records.forEach(p=>add(select,new Option(value(p.label,p.id),p.id)));if(!records.length)add(select,new Option('SMARCA2-FX5 · 기존 중성 기본값','SMARCA2-FX5'));select.value=[...select.options].some(o=>o.value===current)?current:(state.catalog?.reference_parents?.default_parent_id||'SMARCA2-FX5');const unavailable=(state.catalog?.reference_parents?.not_ready||[]).length;$('parentHelp').textContent=`ready는 기술 입력 상태이며 과학적 승인이 아닙니다. not-ready/excluded ${unavailable+(state.catalog?.reference_parents?.excluded||[]).length}건`}
function selectedValues(id){return [...$(id).selectedOptions].map(option=>option.value)}
function linkerLength(template){if(/_short$/.test(template.id))return 'short';if(/_long$/.test(template.id))return 'long';return 'medium'}
function selectedLinkerIds(){const templates=state.catalog?.linkers?.templates||[],mode=$('linkerProfile').value;const originals=new Set(['alkyl_c6','peg3','peg_alkyl','piperazine','triazole','aryl_para']);if(mode==='six')return templates.filter(t=>originals.has(t.id)).map(t=>t.id);if(mode==='all')return templates.map(t=>t.id);const families=new Set(selectedValues('linkerFamily')),lengths=new Set(selectedValues('linkerLength'));return templates.filter(t=>families.has(t.family)&&lengths.has(linkerLength(t))).map(t=>t.id)}
function renderCatalog(){const root=$('catalogContent');clear(root);const parents=state.catalog?.reference_parents||{};(parents.available||[]).forEach(p=>{const card=node('article','catalog-item');add(card,node('p','kicker','Available parent'),node('h3','',value(p.label,p.id)),node('p','',`기술 ready · 과학 승인 아님 · ${value(p.source)}`));root.appendChild(card)});[...(parents.not_ready||[]),...(parents.excluded||[])].forEach(p=>{const card=node('article','catalog-item');add(card,node('p','kicker','Not ready / excluded'),node('h3','',value(p.id,p.group_id)),node('p','',value(p.reason)));root.appendChild(card)});(state.catalog?.recruiters?.recruiters||[]).forEach(r=>{const card=node('article','catalog-item');add(card,node('p','kicker',value(r.e3_type)),node('h3','',value(r.id)),node('p','',value(r.description)));const url=safeUrl(r.source_url);if(url){const a=node('a','','출처 열기');a.href=url;a.target='_blank';a.rel='noopener noreferrer';card.appendChild(a)}root.appendChild(card)});const bench=node('article','catalog-item');add(bench,node('p','kicker','CRBN benchmark'),node('h3','',value(state.catalog?.CRBNbenchmark?.prediction_status)),node('p','',`규칙 카탈로그 ${value(state.catalog?.rule_catalog?.length,0)}개`));root.appendChild(bench)}
function parameters(){return {exploratory:$('exploratory').checked,dock:$('dock').checked,use_api:$('useApi').checked&&!$('useApi').disabled,panel_size:Number($('panelSize').value),target:'SMARCA2',parent_id:$('parentId').value,linker_ids:selectedLinkerIds()}}
async function submitDesign(){if(state.readOnly)return;clearError();const params=parameters();if(!params.linker_ids.length){setError('사용자 지정 Linker 구성에서 계열과 길이를 하나 이상 선택해 실제 template을 포함해 주세요.','EMPTY_LINKER_SELECTION');return}show('resultPanel',false);state.result=null;if(!state.pending)state.pending={result_id:new URLSearchParams(location.search).get('result_id')||'design:SMARCA2',operation:'design_panel',parameters:params,request_key:`ui-${crypto.randomUUID()}`};setBusy(true);try{const job=await api('/api/lab/jobs',{method:'POST',headers:{'Content-Type':'application/json','X-TPD-Local':'1'},body:JSON.stringify(state.pending)});state.pending=null;watch(job)}catch(e){setBusy(false);setError(`${e.message} 같은 요청 키로 다시 실행하면 중복 작업을 만들지 않습니다.`,e.code)}}
function watch(job){state.selectedId=job.id||job.job_id;state.job=job;renderJob(job);setBusy(!terminal.has(job.state));loadJobs(false);if(state.timer)clearTimeout(state.timer);if(!terminal.has(job.state)){show('resultPanel',false);state.timer=setTimeout(()=>pollJob(job.id||job.job_id),1400)}else if(job.state==='completed')loadResult(job)}
async function pollJob(id){if(!id)return;try{const response=await api(`/api/lab/jobs/${encodeURIComponent(id)}`);if(state.selectedId&&state.selectedId!==id)return;watch(response)}catch(e){setError(e.message,e.code);state.timer=setTimeout(()=>pollJob(id),2500)}}
function renderJob(job){const status=value(job.state,'queued'),id=job.id||job.job_id;$('jobState').textContent=status;$('jobState').dataset.state=status;const review=$('scientificReviewLink');review.href=id?`/scientific-review/${encodeURIComponent(id)}`:'#';review.classList.toggle('hidden',status!=='completed'||!id);show('progressWrap',!terminal.has(status));$('stageText').textContent=value(job.stage||job.current_stage,status);const p=Number(job.progress);if(Number.isFinite(p)){$('progress').value=p<=1?p*100:p;$('progressText').textContent=`${Math.round($('progress').value)}%`}else{$('progress').removeAttribute('value');$('progressText').textContent='단계 진행 중'}if(['failed','held','interrupted'].includes(status))setError(job.error?.message||job.message||`작업이 ${status} 상태로 종료되었습니다.`,job.error_code||job.error?.code||status.toUpperCase())}
async function cancelJob(){const id=state.job?.id||state.job?.job_id;if(!id)return;try{watch(await api(`/api/lab/jobs/${encodeURIComponent(id)}/cancel`,{method:'POST',headers:{'X-TPD-Local':'1'}}))}catch(e){setError(e.message,e.code)}}
async function loadJobs(resume=true){try{const resultId=new URLSearchParams(location.search).get('result_id')||'design:SMARCA2';const data=await api(`/api/lab/jobs?result_id=${encodeURIComponent(resultId)}`);const jobs=(Array.isArray(data)?data:(data.jobs||[])).filter(j=>j.operation==='design_panel');const select=$('jobHistory');const chosen=select.value;clear(select);add(select,new Option('작업을 선택하세요',''));jobs.forEach(j=>add(select,new Option(`${value(j.state)} · ${value(j.id||j.job_id)}`,j.id||j.job_id)));select.value=chosen;if(resume){const active=jobs.find(j=>!terminal.has(j.state));if(active)watch(active);else if(jobs[0]){renderJob(jobs[0]);if(jobs[0].state==='completed')loadResult(jobs[0])}}}catch(e){setError(e.message,e.code)}}
async function loadResult(job){const id=job.id||job.job_id;try{const full=job.freshness?job:await api(`/api/lab/jobs/${encodeURIComponent(id)}`);if(state.selectedId&&state.selectedId!==id)return;if(full.freshness?.current===false)setError('이 결과는 이전 코드 또는 입력 버전으로 생성된 기록입니다. 현재 실행 결과로 간주하지 말고 새 실행 결과와 구분해 검토하세요.','PREVIOUS_VERSION');state.result=full.result||full.output||full.result_record;if(state.result)renderResult()}catch(e){setError(e.message,e.code)}}
function metric(label,val){const c=node('article','scorecard');add(c,node('span','',label),node('strong','',value(val)));return c}
function renderResult(){state.page=1;const r=state.result;show('resultPanel',true);const parent=r.parent_scope?.selected_parent_title||r.parent_scope?.actual_design_parent_id||r.warhead?.id;$('resultTitle').textContent=`${value(parent)} 설계 가설 · 검토 대기`;$('analogTitle').textContent=`${value(parent)} 선택 analog`;$('resultId').textContent=`${value(r.candidate_id)} · ${value(r.status)} · 6HAZ 고정 receptor frame`;const s=r.summary||{},scores=$('scorecards');clear(scores);add(scores,metric('유효 분자 그래프',s.raw_graph_analogs),metric('선택 analog',s.selected_analogs),metric('원 설계 조립 구조 가설',s.protac_count),metric('실제 qualified',s.qualified_analogs));$('warheadState').textContent=value(r.warhead?.chemical_state||r.parent_scope?.selected_parent_input_role);renderDownloads(r.files||{});renderCalibration(r.calibration||{});renderBranches(r);renderCandidates();renderAnalogs(r.analogs||[]);renderAtoms(r.sites?.atoms||[]);renderReview(r);window.TPDDesignEvidence?.render(state.catalog,r);$('resultPanel').scrollIntoView({behavior:'smooth'})}
function renderDownloads(files){const root=$('downloads');clear(root);[['전체 JSON',files.json],['보고서',files.report],['SDF',files.sdf],['Warheads',files.warheads]].forEach(([label,ref])=>{const url=artifactUrl(ref);if(url){const a=node('a','download-button',label);a.href=url;a.setAttribute('download','');root.appendChild(a)}})}
function renderCalibration(c){const root=$('calibration');clear(root);const labels={reference_ready_prediction_not_run:'기준 구조 확보 / 새 예측 대기',existing_C01_C02_saved_benchmark_separate_from_new_panel:'기존 C01/C02 저장 benchmark · 새 설계와 별도'};['CRBN','VHL'].forEach(name=>add(root,node('span','badge neutral',`${name} · ${labels[c[name]?.status]||value(c[name]?.status,'상태 미보고')}`)))}
function renderBranches(r){const root=$('branchSummary');clear(root);const counts=r.summary?.branch_counts||{};['CRBN','VHL'].forEach(name=>{const c=node('article',`branch ${name.toLowerCase()}`);add(c,node('p','kicker',name),node('strong','',value(counts[name],0)),node('span','','원 설계 생성 시점의 구조 가설 · 과학적 승인 아님 · 합성·효능 미검증'));root.appendChild(c)});const linkers=[...new Set((r.protac_candidates||[]).map(x=>x.linker_id).filter(Boolean))];const f=$('linkerFilter');clear(f);add(f,new Option('전체','all'));linkers.forEach(x=>add(f,new Option(x,x)))}
function renderCandidates(){const all=state.result?.protac_candidates||[],e3=$('e3Filter').value,linker=$('linkerFilter').value;const list=all.filter(c=>(e3==='all'||c.e3_type===e3)&&(linker==='all'||c.linker_id===linker));const start=(state.page-1)*12,root=$('candidateGrid');clear(root);list.slice(start,start+12).forEach(c=>{const card=node('article','candidate-card');const imgUrl=artifactUrl(c.files?.image,true);if(imgUrl){const img=node('img');img.src=imgUrl;img.loading='lazy';img.alt=`${value(c.candidate_id)} 2D 구조`;card.appendChild(img)}add(card,node('span',`e3-tag ${String(c.e3_type||'').toLowerCase()}`,value(c.e3_type)),node('h4','',value(c.candidate_id)),smilesDetails(c.canonical_smiles),node('p','',`${value(c.warhead_analog_id)} · ${value(c.linker_id)}`),node('small','',`MW ${value(c.identity?.properties?.molecular_weight_Da)} · TPSA ${value(c.identity?.properties?.TPSA_A2)} Å²`),node('small','',`조립 ${(c.assembly_mode==='pose_supported_hypothesis'?'warhead 도킹 기준 통과':'도킹 미통과/미실시 · 그래프 미리보기')} · 합성·효능 ${'미검증'} · 삼중복합체 ${'미실행(원 설계 생성 시점의 기록)'}; 후속 계산·검수는 과학적 준비도 검토에서 확인`));const sdf=artifactUrl(c.files?.sdf);if(sdf){const a=node('a','small-download','SDF 다운로드');a.href=sdf;card.appendChild(a)}root.appendChild(card)});renderPages(Math.ceil(list.length/12))}
function smilesDetails(smiles){const box=node('details');add(box,node('summary','','SMILES 보기'),node('p','mono',value(smiles)));return box}
function renderPages(total){const root=$('pagination');clear(root);if(total<2)return;const prev=node('button','','이전'),next=node('button','','다음');prev.disabled=state.page===1;next.disabled=state.page>=total;prev.addEventListener('click',()=>{state.page--;renderCandidates()});next.addEventListener('click',()=>{state.page++;renderCandidates()});add(root,prev,node('span','',`${state.page} / ${total}`),next)}
function renderAnalogs(items){const root=$('analogRows');clear(root);items.filter(x=>x.selected).forEach(a=>{const tr=node('tr');const image=node('td'),url=artifactUrl(a.files?.image,true);if(url){const img=node('img','table-image');img.src=url;img.loading='lazy';img.alt=`${value(a.id)} 2D 구조`;image.appendChild(img)}[image,node('td','mono',value(a.id)),node('td','',value(a.transformation_class)),node('td','',`${value(a.tier)} / ${value(a.confidence)}`),node('td','',value(a.site_status)),node('td','',`${value(a.docking?.status)} · 기하 기준 ${a.assembly_eligible?'통과':'미통과/미실시'} · RMSD ${value(a.docking?.best_core_rmsd_A)} Å`),node('td','',value(a.design_hypothesis))].forEach(x=>tr.appendChild(x));root.appendChild(tr)})}
function renderAtoms(atoms){const root=$('atomList');clear(root);atoms.forEach(a=>{const item=node('article','atom-card');add(item,node('h4','',`Atom map ${value(a.atom_map)}`),node('p','',`${value(a.state)} · SAR ${value(a.SAR?.status)}`),node('p','',`SASA ${value(a.SASA_complex_A2)} Å² · 최근접 단백질 원자 ${value(a.nearest_protein_heavy_atom_A)} Å`),node('small','',`선택: ${value(a.why_selected)} / 제외: ${value(a.why_excluded)}`),node('small','',`HBD ${value(a.chemical_HBD)} · HBA ${value(a.chemical_HBA)}`));root.appendChild(item)})}
function renderReview(r){const root=$('reviewContent');clear(root);[['계산 범위',[`분자 그래프 ${r.summary.raw_graph_analogs}개에서 입체이성질체 ${r.summary.valid_analogs}개를 기록했습니다. 입체화학 미확정 ${r.analogs.filter(x=>x.stereochemistry?.unresolved_stereo_count).length}개는 도킹 대표 선별에서 제외했습니다.`]],['검토 질문',r.review_questions],['한계',r.limitations],['API 추가 질문',r.ai?.review_questions],['AI 상태',[value(r.ai?.status)]],['API 검토 메모',r.ai?.notes]].forEach(([title,items])=>{const section=node('section');add(section,node('h4','',title));const ul=node('ul');(items||[]).forEach(x=>add(ul,node('li','',x)));add(section,ul);root.appendChild(section)})}
function presetNotice(text){$('notice').textContent=`${text} 조건을 채웠습니다. 검토 후 실행 버튼을 눌러 주세요.`;show('notice',true);state.pending=null}
function selectAll(id,on=true){[...$(id).options].forEach(option=>{option.selected=on})}
function clearCurrentResult(){if(state.timer)clearTimeout(state.timer);state.timer=null;state.selectedId=null;state.currentView=null;state.pending=null;state.result=null;state.job=null;show('resultPanel',false);setBusy(false);window.TPDDesignEvidence?.render(state.catalog,null);history.replaceState({},'',location.pathname);loadJobs(false);$('designEvidencePanel').scrollIntoView({behavior:'smooth'})}
$('designForm').addEventListener('submit',e=>{e.preventDefault();submitDesign()});$('cancelButton').addEventListener('click',cancelJob);$('refreshButton').addEventListener('click',()=>loadJobs(false));$('closeCatalog').addEventListener('click',()=>show('catalogPanel',false));$('referenceExample').addEventListener('click',()=>loadCatalog(true));$('clearResultButton').addEventListener('click',clearCurrentResult);
$('strictExample').addEventListener('click',()=>{$('parentId').value='SMARCA2-FX5';$('exploratory').checked=false;$('dock').checked=true;$('panelSize').value='10';$('linkerProfile').value='six';$('useApi').checked=false;updateRunLabel();presetNotice('엄격 preset')});
$('dualExample').addEventListener('click',()=>{$('exploratory').checked=true;$('dock').checked=true;$('panelSize').value='12';$('linkerProfile').value='custom';selectAll('linkerFamily',false);['PEG','PEG-alkyl','piperazine'].forEach(v=>{const option=[...$('linkerFamily').options].find(x=>x.value===v);if(option)option.selected=true});selectAll('linkerLength',true);presetNotice('탐색 preset')});
$('previewExample').addEventListener('click',()=>{$('exploratory').checked=true;$('dock').checked=false;$('useApi').checked=false;$('panelSize').value='10';$('linkerProfile').value='six';updateRunLabel();presetNotice('No-dock graph preview · microstates preset')});
$('jobHistory').addEventListener('change',e=>{if(e.target.value){clearTimeout(state.timer);state.selectedId=e.target.value;pollJob(e.target.value)}});['e3Filter','linkerFilter'].forEach(id=>$(id).addEventListener('change',()=>{state.page=1;renderCandidates()}));$('useApi').addEventListener('change',updateRunLabel);['parentId','exploratory','dock','useApi','panelSize','linkerProfile','linkerFamily','linkerLength'].forEach(id=>$(id).addEventListener('input',()=>{state.pending=null}));
Promise.allSettled([loadHealth(),loadCatalog(false)]).then(()=>loadJobs(true));
