(()=>{
'use strict';
const $ = id => document.getElementById(id);
const state = {health:{}, cases:[], data:null, jobs:[], selected:null, viewer:null, models:[], pending:null, busy:false, timer:null};
const labels = {queued:'대기',running:'실행 중',completed:'완료',review_ready:'검토 초안 준비',held:'확인 필요',failed:'실패',cancelled:'중단',interrupted:'실행 중단됨'};
const active = j => ['queued','running'].includes(j.state);
const number = v => v == null ? '미확인' : Number(v).toLocaleString('ko-KR',{maximumFractionDigits:3});
const when = v => v ? new Date(v).toLocaleString('ko-KR') : '';
function el(tag,text,cls) {const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function link(text,href,cls) {const a=el('a',text,cls);a.href=href;return a;}
function download(ref,name) {const a=link(name,'/api/artifacts/'+encodeURIComponent(ref.artifact_id)+'/download','download');a.download=name;return a;}
let toastTimer;
function toast(message,error=false) {clearTimeout(toastTimer);if(!error)toastTimer=setTimeout(()=>{$('toast').hidden=true;},8000);$('toast').textContent=message;$('toast').hidden=false;$('toast').className=error?'error-message':'';}
async function api(path,body) {const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-TPD-Local':'1'},body:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw new Error('서버 응답을 읽지 못했습니다. 실행 이력을 먼저 확인해 주세요.');}if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'입력 또는 서버 상태를 확인해 주세요.');return d;}
function show(page) {document.querySelectorAll('.page').forEach(n=>n.hidden=n.id!=='page-'+page);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));if(page==='structures'&&state.viewer)state.viewer.resize();}
function badge(job) {return el('span',labels[job.state]||job.state,'tag '+(['completed','review_ready'].includes(job.state)?'green':['held','failed','interrupted'].includes(job.state)?'amber':''));}
function busy() {if($('design-lab-link')&&state.data)$('design-lab-link').href='/design?result_id='+encodeURIComponent(state.data.id);const locked=state.busy||state.jobs.some(active)||!state.data||state.data.replay_only||state.health.read_only||state.health.review_only;document.querySelectorAll('.action,form button[type=submit]').forEach(n=>n.disabled=locked||(n.dataset.tool==='review'&&!state.health.llm_enabled));$('case-select').disabled=state.busy;}
function rowList(parent,jobs) {parent.replaceChildren();if(!jobs.length){parent.append(el('p','아직 실행한 작업이 없습니다.','empty'));return;}for(const job of jobs){const b=el('button',null,'job-row'+(job.id===state.selected?' selected':''));const left=el('div');left.append(el('strong',job.title),el('small',when(job.created_at)));b.append(left,badge(job));b.onclick=()=>{show('agents');selectJob(job.id);};parent.append(b);}}
function renderJobs() {rowList($('recent-jobs'),state.jobs.slice(0,4));rowList($('jobs-list'),state.jobs);$('job-count').textContent=state.jobs.length+'개';const latest=state.jobs.find(j=>j.operation==='review');$('metric-agent').textContent=latest?labels[latest.state]:'실행 가능';$('metric-agent-note').textContent=latest?`${latest.calls}회 호출 · ${number(latest.total_tokens)} 토큰`:'현재 자료를 API로 검토합니다';renderCandidates();busy();}
function prototypeResult(r) {return r.transformation?.kind==='linker_boundary_methylene_extension';}
function transformationText(r) {return prototypeResult(r)?`메틸렌 ${r.transformation.added_methylene_count}개 추가`: `${r.transformation.label} · ${r.transformation.orientation==='reverse'?'역방향':'정방향'}`;}
let linkerCatalog={templates:[]};
function updateLinkerHint(){const id=$('design-linker').value,legacy=id.startsWith('legacy:');const template=linkerCatalog.templates.find(t=>t.id===id);$('design-orientation').disabled=legacy;if(legacy)$('design-orientation').value='forward';$('linker-design-hint').textContent=legacy?'초기 linker perturbation 기능 검증용 prototype입니다. CH₂ 길이 연장의 작동 확인이며 신규 효능 후보로 승격되지 않습니다.':(template?template.rationale+' '+template.state_review:'선택한 linker를 확인하세요.');}
async function loadLinkerLibrary(){linkerCatalog=await api('/api/lab/linker-library');const select=$('design-linker');select.replaceChildren();for(const t of linkerCatalog.templates){const o=el('option',t.label);o.value=t.id;select.append(o);}const old=el('optgroup');old.label='기존 prototype 재현';for(const n of [1,2]){const o=el('option',`기능 검증 prototype · +${n}CH₂`);o.value='legacy:'+n;old.append(o);}select.append(old);select.onchange=updateLinkerHint;updateLinkerHint();}
function renderCandidates() {
 const node=$('candidate-results');node.replaceChildren();const seen=new Set();
 const jobs=state.jobs.filter(j=>{const key=j.result?.candidate_id+JSON.stringify(j.parameters);if(j.operation!=='candidate'||j.state!=='completed'||!j.result||seen.has(key))return false;seen.add(key);return true;});
 const unique=new Set(jobs.map(j=>j.result.candidate_id));$('design-status').textContent=jobs.length?`${unique.size}개 구조 · ${jobs.length}개 설계 기록`:'설계 가설 생성 가능';
 if(!jobs.length){node.append(el('p','아직 생성한 설계 가설이 없습니다.','empty'));return;}
 for(const j of jobs){const r=j.result,c=el('article',null,'panel candidate-card');
  c.append(el('span',prototypeResult(r)?'초기 linker perturbation 기능 검증용 prototype':'Linker 설계 가설 · 검토 대기','tag amber'),el('h3',r.candidate_id));
  const img=el('img');img.src='/api/lab/artifacts/'+r.files.image.artifact_id+'/preview';img.alt=r.candidate_id+'의 2D 분자 구조';img.loading='lazy';c.append(img,el('p',r.parent_candidate+' 기준 · '+transformationText(r)));
  const ident=r.identity;c.append(el('p',`분자량 ${number(ident.properties?.molecular_weight_Da)} Da · TPSA ${number(ident.properties?.TPSA_A2)} Å² · 회전 결합 ${number(ident.properties?.rotatable_bonds_RDKit_strict)}`,'hint'));
  if(r.linker_comparison){const v=r.linker_comparison;c.append(el('p',`Linker 중원자 ${v.parent.heavy_atom_count} → ${v.hypothesis.heavy_atom_count} · 고리 ${v.parent.ring_count} → ${v.hypothesis.ring_count}`,'hint'));const delta=v.whole_molecule_property_delta;c.append(el('p',`부모 대비 Δ분자량 ${number(delta.molecular_weight_Da)} Da · ΔTPSA ${number(delta.TPSA_A2)} Å² · Δ회전 결합 ${number(delta.rotatable_bonds_RDKit_strict)}`,'hint'));}
  const refs=el('div',null,'downloads');refs.append(download(r.files.sdf,'구조.sdf'),download(r.files.smiles,'SMILES.smi'),download(r.files.image,'구조.png'));c.append(refs,el('p','2D 설계 · 실제 GPU 결합 구조/복합체 접촉 미실시 · 합성·효능 미검증','scope-note'));
  const detail=el('details');detail.append(el('summary','변경 근거·연결 부위·다음 검토'),el('p',r.rationale));
  if(r.attachments)for(const a of r.attachments)detail.append(el('p',`${a.role} 원자 map ${a.retained_atom_map} (${a.element}) 유지 · ${a.bond_kind} 연결 · 신규 exit-vector 판정 아님`));
  if(r.chemical_state_review)detail.append(el('p',r.chemical_state_review));
  if(r.design_evidence){detail.append(el('p','문헌 motif를 참고한 개발 템플릿입니다. 해당 논문 화합물/합성 경로를 그대로 추출한 라이브러리가 아닙니다.'));for(const source of r.design_evidence.sources){const link=el('a','근거 DOI '+source.doi);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';detail.append(link,el('br'));}}
  detail.append(el('p',r.remaining.join(' · ')));c.append(detail);node.append(c);
 }
}
async function selectJob(id) {state.selected=id;renderJobs();try{const job=await api('/api/lab/jobs/'+encodeURIComponent(id));if(state.selected!==id)return;renderDetail(job);}catch(e){toast(e.message,true);}}
function renderDetail(job) {const box=$('job-detail');box.className='';box.replaceChildren();box.append(el('h3',job.title),badge(job),el('p',`시작 ${when(job.created_at)} · 시도 ${job.attempt}`,'hint'),el('p',`API ${job.calls}회 · ${number(job.total_tokens)} 토큰 · ${job.stage.startsWith('agent_call_')?'AI 호출 '+job.stage.split('_').pop():({queued:'실행 대기',checking_inputs:'입력 확인',finished:'종료',server_restarted:'서버 재시작',cancel_requested:'중단 요청',worker_busy:'다른 실행 대기'}[job.stage]||job.stage)}`,'hint'));
 if(job.freshness&&!job.freshness.current)box.append(el('p','이후 입력 또는 처리 코드가 변경되었습니다. 이 결과는 당시 자료의 기록입니다.','notice'));
 if(job.usage_status==='unreconciled')box.append(el('p','API 응답 또는 사용량 확인이 끝나지 않았습니다. 중복 호출을 막기 위해 자동 재시도하지 않습니다.','notice'));
 if(job.error_code)box.append(el('p','확인 코드: '+job.error_code,'error-message'));
 if(active(job)){box.append(el('p','작업 중입니다. AI 호출 중 중단하면 이미 보낸 호출의 응답까지 기록한 뒤 멈춥니다.','notice'));const b=el('button','작업 중단','secondary');b.onclick=async()=>{try{await api('/api/lab/jobs/'+job.id+'/cancel',{});await refreshJobs();}catch(e){toast(e.message,true);}};box.append(b);}
 else if(['held','failed','interrupted','cancelled'].includes(job.state)&&job.usage_status!=='unreconciled'&&!state.health.read_only&&!state.data.replay_only){const b=el('button','현재 입력으로 다시 실행','secondary');b.disabled=state.jobs.some(active);b.onclick=()=>start(job.operation,job.parameters,job.id);box.append(b);}
 if(job.outputs?.length){const refs=el('div',null,'downloads');for(const o of job.outputs)refs.append(download(o.ref,o.name));box.append(refs);}
 const r=job.result;if(!r)return;
 if(r.claims){box.append(el('h3','검토 초안'));for(const claim of r.claims){const c=el('article',null,'claim');c.append(el('span',claim.candidate_id+' · '+claim.kind,'tag'),el('p',claim.interpretation),el('small','근거: '+claim.citations.map(x=>x.source_id).join(', ')));box.append(c);}box.append(el('p','AI 검토 초안입니다. 전문가 판정이나 실행 승인으로 기록되지 않습니다.','notice'));}
 else if(job.operation==='verify')box.append(el('p',`${number(r.files_verified)}개 파일의 해시와 연결을 확인했습니다.`));
 else if(job.operation==='chemistry'){box.append(el('h3','수소 방향 시험 결과'),el('p',`${r.candidate_id} · ${r.status}`),el('p',`중원자 최대 이동 ${number(r.heavy_atom_max_displacement_A)} Å`));const energy=r.ligand_forcefield_energy_kcal_mol;box.append(el('p',`국소 힘장 진단 ${number(energy.before)} → ${number(energy.after)} kcal/mol`,'hint'),el('p','이 에너지는 결합 에너지나 효능 점수가 아닙니다.','notice'));for(const t of r.limitations)box.append(el('p',t,'hint'));}
 const raw=el('details');raw.append(el('summary','기록 JSON 보기'));const pre=el('pre',JSON.stringify(r,null,2));raw.append(pre);box.append(raw);
}
async function refreshJobs() {if(!state.data)return;const caseId=state.data.id;const jobs=await api('/api/lab/jobs?result_id='+encodeURIComponent(caseId));if(state.data.id!==caseId)return;state.jobs=jobs;renderJobs();if(state.selected)await selectJob(state.selected);schedule();}
function schedule() {clearTimeout(state.timer);if(state.jobs.some(active))state.timer=setTimeout(async()=>{try{await refreshJobs();if(!state.jobs.some(active))await refreshCase(false);}catch(e){toast(e.message,true);}},3000);}
async function start(operation,parameters={},retry_of=null) {if(state.busy||!state.data)return;state.busy=true;busy();show('agents');const base={result_id:state.data.id,operation,parameters,retry_of};const fingerprint=JSON.stringify(base);if(state.pending?.fingerprint!==fingerprint)state.pending={fingerprint,body:{...base,request_key:'ui-'+crypto.randomUUID()}};try{const result=await api('/api/lab/jobs',state.pending.body);state.pending=null;state.selected=result.job_id;toast('작업을 등록했습니다. 이 화면에서 진행 상황을 확인할 수 있습니다.');await refreshJobs();}catch(e){toast(e.message+' 같은 작업을 다시 누르면 동일 요청으로 확인합니다.',true);}finally{state.busy=false;busy();}}
function sampleText(s) {const x=s.reported_execution?.settings||{};return `${x.use_potentials?'ON · 보조':'OFF · 주 비교'} / seed ${x.seed??'미확인'} / rank ${s.rank}`;}
function sampleOptions() {const id=$('structure-candidate').value,c=state.data?.candidates.find(x=>x.compound_id===id);$('structure-sample').replaceChildren();(c?.samples||[]).forEach((s,i)=>{const o=el('option',sampleText(s));o.value=i;$('structure-sample').append(o);});}
function renderSamples() {const table=el('table'),head=el('thead'),hr=el('tr');for(const x of ['후보 / 샘플','표적 RMSD Å','VHL RMSD Å','Confidence','접촉 검사'])hr.append(el('th',x));head.append(hr);table.append(head);const body=el('tbody');for(const c of state.data.candidates){c.samples.forEach((s,i)=>{const row=el('tr'),cell=el('td'),b=el('button',c.compound_id+' · '+sampleText(s),'text-button');b.onclick=()=>{$('structure-candidate').value=c.compound_id;sampleOptions();$('structure-sample').value=i;show('structures');loadStructure();};cell.append(b);row.append(cell,el('td',number(s.summary.target_rmsd_A)),el('td',number(s.summary.vhl_rmsd_after_target_alignment_A)),el('td',number(s.summary.confidence_score)),el('td',s.status.contacts==='completed_with_limits'?'제한 있음':s.status.contacts));body.append(row);});}table.append(body);$('samples-table').replaceChildren(table);}
function renderEvidence() {const reports=$('reports-list');reports.replaceChildren();for(const r of state.data.reports||[]){const wrap=el('div',null,'report-row');wrap.append(el('p',when(r.created_at)),el('span',r.freshness?.current?'현재 입력':'당시 입력 · 변경 있음','tag'),download(r.markdown_ref,'통합 보고서.md'),link('검토 기록 ↗','/human-review/'+r.id));reports.append(wrap);}if(!reports.childNodes.length)reports.append(el('p','현재 입력으로 통합 보고서를 작성할 수 있습니다.','empty'));
 $('source-link').href='/saved-review/'+state.data.dossier_id;$('replay-link').href='/api/lab/cases/'+state.data.id+'/replay';
 const reviews=$('expert-reviews');reviews.replaceChildren();for(const item of state.data.expert_reviews){const r=item.assessment||item;const card=el('article',null,'panel');card.append(el('h2',r.reviewer_name||r.reviewer?.name||'전문가 회신'),el('p','원문 의견 수신 · 정식 과학 승인과 별도','tag amber'));if(item.source_ref)card.append(download(item.source_ref,'전문가 회신.docx'));const questions=r.questions||r.responses||[];for(const q of Array.isArray(questions)?questions:Object.values(questions)){const d=el('details');d.append(el('summary',(q.question_id||q.id||'검토 의견')+' · '+(q.title||q.topic||({Q01:'원자형과 수소결합 역할',Q02:'화학 상태와 수소 방향',Q03:'구조 비교의 해석',Q04:'문헌 조건과 결측',Q05:'합성 근거와 신규 설계'}[q.question_id]||''))),el('p',q.answer_original||q.answer||q.opinion||''));for(const k of ['applied','remaining','implementation_response'])if(q[k])d.append(el('p',({applied:'반영 내용',remaining:'남은 확인',implementation_response:'개발 답변'}[k])+': '+(typeof q[k]==='string'?q[k]:q[k].join(' · '))));card.append(d);}if(!questions.length){const d=el('details');d.append(el('summary','회신과 반영 내용 보기'),el('pre',JSON.stringify(r,null,2)));card.append(d);}reviews.append(card);}}
async function refreshCase(reset=true) {const id=$('case-select').value;if(!id)return;const d=await api('/api/lab/cases/'+encodeURIComponent(id));if($('case-select').value!==id)return;state.data=d;if(reset){state.selected=null;$('job-detail').replaceChildren(el('p','왼쪽에서 작업을 선택하세요.','empty'));if(state.viewer)state.viewer.removeAllModels();state.models=[];sampleOptions();}const info=state.cases.find(c=>c.id===id);$('case-title').textContent=info?.title||'연구 사례';$('metric-candidates').textContent=d.summary.candidate_count;$('metric-samples').textContent=d.summary.sample_count;$('metric-reviews').textContent=d.expert_reviews.length+'건';$('mode-badge').textContent=d.replay_only||state.health.read_only?'저장 자료 재생':'로컬 실행';renderSamples();renderEvidence();await refreshJobs();}
function styleModels() {const colors={target:0x439ba4,vhl:0x9368c2,warhead:0xe3a237,linker:0xd05d85,recruiter:0x4a9c65,complex_partner:0x9aabae};for(const item of state.models){item.model.setStyle({},{});if(!$(item.reference?'show-reference':'show-prediction').checked)continue;for(const [part,color] of Object.entries(colors)){const serial=item.atoms.filter(a=>a.part===part).map(a=>a.serial);const ligand=['warhead','linker','recruiter'].includes(part);item.model.setStyle({serial},{stick:{color,radius:ligand?0.20:0.10,opacity:item.reference?0.35:1},...(ligand?{sphere:{color,scale:0.20,opacity:item.reference?0.35:1}}:{})});}}state.viewer.render();}
async function loadStructure() {if(!state.data)return;const b=$('load-structure');b.disabled=true;const selected={id:state.data.id,cid:$('structure-candidate').value,index:$('structure-sample').value};$('structure-notice').textContent='원본 해시와 정렬 정보를 확인하고 있습니다…';try{const data=await api(`/api/lab/structures/${selected.id}/${selected.cid}/${selected.index}`);if(state.data.id!==selected.id||$('structure-candidate').value!==selected.cid||$('structure-sample').value!==selected.index)return;if(!window.$3Dmol)throw new Error('3D 뷰어를 불러오지 못했습니다. 저장 자료와 지표는 계속 확인할 수 있습니다.');if(!state.viewer){$('viewer').replaceChildren();state.viewer=$3Dmol.createViewer($('viewer'),{backgroundColor:'#f7faf8',antialias:true});}state.viewer.removeAllModels();state.models=[];for(const [reference,atoms] of [[true,data.reference_atoms],[false,data.predicted_atoms]]){const model=state.viewer.addModel();model.addAtoms(atoms);state.models.push({model,reference,atoms});}styleModels();state.viewer.zoomTo();state.viewer.resize();state.viewer.render();$('structure-notice').textContent=`실험 구조 ${data.reference_pdb} · 표적 정렬 1회 · 원자 대응 ${data.mapping_count}가지 중 0번 표시 · 단백질 Cα / 리간드 중원자`;
 const metrics=$('structure-metrics');metrics.className='';metrics.replaceChildren();for(const [name,value] of [['표적 RMSD',data.summary.target_rmsd_A],['VHL RMSD',data.summary.vhl_rmsd_after_target_alignment_A],['Confidence',data.summary.confidence_score]]){const row=el('div',null,'metric-row');row.append(el('span',name),el('strong',number(value)+(name.includes('RMSD')?' Å':'')));metrics.append(row);}for(const [part,v] of Object.entries(data.parts)){metrics.append(el('p',`${part} ${v.map(number).join('–')} Å`));}metrics.append(el('p','부위별 범위의 양 끝은 서로 다른 대칭 원자 대응일 수 있습니다.','hint'),download(data.comparison_ref,'정렬 근거.json'),download(data.prediction_ref,'예측 구조.cif'),download(data.reference_ref,'실험 구조.cif'));
 }catch(e){$('structure-notice').textContent=e.message;toast(e.message,true);}finally{b.disabled=false;}}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>show(n.dataset.page));document.querySelectorAll('.action').forEach(n=>n.onclick=()=>start(n.dataset.tool));$('goto-chemistry').onclick=()=>show('design');$('goto-jobs').onclick=()=>show('agents');$('case-select').onchange=()=>refreshCase().catch(e=>toast(e.message,true));$('refresh').onclick=()=>refreshCase(false).catch(e=>toast(e.message,true));$('structure-candidate').onchange=sampleOptions;$('load-structure').onclick=loadStructure;$('reset-view').onclick=()=>{if(state.viewer){state.viewer.zoomTo();state.viewer.render();}};['show-reference','show-prediction'].forEach(id=>$(id).onchange=()=>{if(state.viewer)styleModels();});window.addEventListener('resize',()=>state.viewer?.resize());
$('candidate-form').onsubmit=e=>{e.preventDefault();const id=$('design-linker').value;if(!id)return;const parameters=id.startsWith('legacy:')?{parent:$('design-parent').value,linker_extension:Number(id.split(':')[1])}:{parent:$('design-parent').value,linker_id:id,orientation:$('design-orientation').value};start('candidate',parameters);};$('chemistry-form').onsubmit=e=>{e.preventDefault();start('chemistry',{candidate_id:$('chemistry-candidate').value,sample_index:0});};
busy();
(async()=>{try{state.health=await api('/api/health');await loadLinkerLibrary();state.cases=await api('/api/lab/cases');$('connection').textContent=state.health.read_only?'저장 자료 재생 · 읽기 전용':state.health.llm_enabled?'API 사용 설정됨':'저장 자료 · CPU 사용';if(state.health.read_only){const note=el('p','이 화면은 전달받은 저장 사례의 읽기 전용 재생입니다. 구조·보고서·이전 실행 결과를 확인할 수 있습니다. 새 CPU 시험은 전달본의 실행 안내를 따라 별도 결과로 확인하세요.','notice');document.querySelector('.main-content').prepend(note);document.querySelector('.hero-note h3').textContent='저장된 AI 검토 읽기';document.querySelector('.hero-note p').textContent='이미 실행한 검토 초안과 근거, 사용량을 확인하세요.';document.querySelector('.hero-note .action').hidden=true;document.querySelector('.hero-note small').textContent='열람에는 새 API 호출이 없습니다.';const open=el('button','저장된 실행 열기','primary');open.onclick=()=>show('agents');document.querySelector('.hero-note').append(open);}$('case-select').replaceChildren();for(const c of state.cases){const option=el('option',c.title);option.value=c.id;$('case-select').append(option);}if(state.cases.length)await refreshCase();else toast('등록된 구조 사례가 없습니다. 문헌 탐색 화면에서 새 연구를 시작할 수 있습니다.');busy();}catch(e){$('connection').textContent='연결 확인 필요';toast(e.message,true);}})();

})();
